(G-CODE GENERATED BY FLATCAM v8.991 - www.flatcam.org - Version Date: 2019/12/27)

(Name: MasterModule.drl_cnc_3mm)
(Type: G-code from Excellon)
(Units: MM)

(Created on Wednesday, 17 June 2026 at 16:18)

(Feedrate: 300.0 mm/min)
(Feedrate rapids 1500.0 mm/min)

(Z_Cut: -1.8 mm)
(Z_Move: 2.0 mm)
(Z Toolchange: 15.0 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 0.5 mm)
(Steps per circle: 64)
(Preprocessor Excellon: grbl_11)
(X range:    1.5000 ...   48.5000  mm)
(Y range:  -68.5000 ...   -1.5000  mm)

(Spindle Speed: 9600.0 RPM)

G21
G90
G17
G94




G01 F300.00
G00 Z2.0000

M03 S9600.0
G00 X2.5000 Y-2.5000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X47.5000 Y-2.5000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X47.5000 Y-67.5000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
G00 X2.5000 Y-67.5000
G01 Z-1.8000
G01 Z0
G00 Z2.0000
M05
G00 Z0.50
G00 X0.0 Y0.0

