#ifndef BUS_CONNECTION_H
#define BUS_CONNECTION_H

enum CommandsID {
    COMMAND_STOP = 0x1,
    COMMAND_START = 0x2
};

enum MessageType {
    REGISTRATION_REQUEST = 0x10,
    REGISTRATION_SUCCESS = 0x11,
    REGISTRATION_DECLINED = 0x12,

    FORWARD_LOCK_REACHED = 0x13,
    FORWARD_LOCK_RELEASED = 0x14,
    REVERSE_LOCK_REACHED = 0x15,
    REVERSE_LOCK_RELEASED = 0x16,

    DATA_PACKAGE = 0x20,

    ATTENDANCE_REQUEST = 0x30,
    ATTENDANCE_RESPONSE = 0x31
};



#endif